export const MYPAGE_REVIEW_MOCK_DATA = [
  {
    teamId: 1,
    id: 1,
    score: 5,
    comment: 'Great event!',
    createdAt: '2024-09-20T05:52:00.441Z',
    Gathering: {
      teamId: 1,
      id: 1,
      type: 'workshop',
      name: 'React Workshop',
      dateTime: '2024-09-20T05:52:00.441Z',
      location: 'Seoul',
      image: '/images/mock-image.png',
    },
    User: {
      teamId: 1,
      id: 1,
      name: 'Alice',
      image: '/images/mock-image.png',
    },
  },
  {
    teamId: 2,
    id: 2,
    score: 4,
    comment: 'Very informative.',
    createdAt: '2024-09-21T06:00:00.441Z',
    Gathering: {
      teamId: 2,
      id: 2,
      type: 'seminar',
      name: 'JavaScript Seminar',
      dateTime: '2024-09-21T06:00:00.441Z',
      location: 'Busan',
      image: '/images/mock-image.png',
    },
    User: {
      teamId: 2,
      id: 2,
      name: 'Bob',
      image: '/images/mock-image.png',
    },
  },
  {
    teamId: 3,
    id: 3,
    score: 3,
    comment: 'It was okay.',
    createdAt: '2024-09-22T07:30:00.441Z',
    Gathering: {
      teamId: 3,
      id: 3,
      type: 'meetup',
      name: 'Tech Meetup',
      dateTime: '2024-09-22T07:30:00.441Z',
      location: 'Incheon',
      image: '/images/mock-image.png',
    },
    User: {
      teamId: 3,
      id: 3,
      name: 'Charlie',
      image: '/images/mock-image.png',
    },
  },
  {
    teamId: 4,
    id: 4,
    score: 2,
    comment: 'Could be better.',
    createdAt: '2024-09-23T08:45:00.441Z',
    Gathering: {
      teamId: 4,
      id: 4,
      type: 'conference',
      name: 'Tech Conference',
      dateTime: '2024-09-23T08:45:00.441Z',
      location: 'Daegu',
      image: '/images/mock-image.png',
    },
    User: {
      teamId: 4,
      id: 4,
      name: 'David',
      image: '/images/mock-image.png',
    },
  },
  {
    teamId: 5,
    id: 5,
    score: 1,
    comment: 'Not good.',
    createdAt: '2024-09-24T09:15:00.441Z',
    Gathering: {
      teamId: 5,
      id: 5,
      type: 'hackathon',
      name: 'Hackathon Event',
      dateTime: '2024-09-24T09:15:00.441Z',
      location: 'Gwangju',
      image: '/images/mock-image.png',
    },
    User: {
      teamId: 5,
      id: 5,
      name: 'Eve',
      image: '/images/mock-image.png',
    },
  },
];
